applications/persona/urls.py
from django.contrib import admin
from django.urls import path

from .import views


app_name = "persona_app" #Nombre de todo el conjunto de direcciones

urlpatterns = [
    
    path('',views.InicioView.as_view(),name='inicio'),
    path('lista-empleados-admin/',views.ListaEmpleadosAdmin.as_view(),name='lista_empleados_admin'),
    path('lista-todos-empleados/',views.ListAllEmpleados.as_view(),name='lista_empleados'),
    path('lista-por-area/<short_name>',views.ListByArea.as_view(),name='empleados-area'),
    path('lista-por-trabajo/<short_name>',views.ListByJob.as_view()),
    path('buscar-empleado/',views.ListEmpleadByKw.as_view()),
    path('habilidades-empleado/',views.ListHabilidadesEmpleado.as_view()),
    path('ver-empleado/<pk>/',views.EmpleadoDetailView.as_view(),name='detalle-empleado'),
    path('crear-empleado/',views.EmpleadoCreateView.as_view(),name='crear_empleado'),
    path('registro-realizado/',views.SuccessView.as_view(),name='success'),
    path('update-empleado/<pk>/',views.EmpleadoUpdateView.as_view(),name='modificar-empleado'),
    path('eliminar-empleado/<pk>/',views.EmpleadoDeleteView.as_view(),name='eliminar-empleado'),
    path('empleado-eliminado/',views.EmpleadoDeleteView.as_view(),name='eliminado'),
   
    ]

empleado/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.departamento.urls')),
    path('', include('applications.persona.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/persona/models.py
from django.db import models
from applications.departamento.models import Departamento


class Habilidades(models.Model):
    habilidad = models.CharField(verbose_name='Habilidad', max_length=100)

    class Meta:
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades Empleado'
        
    def __str__(self):
            return str(self.id) + ' - ' +  self.habilidad    
      


class Empleado(models.Model): #Modelo para tabla 'Empleado'
    
    JOB_CHOICES = (
        ('1', 'Informatico'),
        ('2', 'Administrador'),
        ('3', 'Economista'),
        ('4', 'Otro'),
    )
    
    first_name = models.CharField(verbose_name='Nombre', max_length=70)
    last_name = models.CharField(verbose_name='Apellidos', max_length=70)
    job = models.CharField(verbose_name='Trabajo', max_length=60, choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    habilidades = models.ManyToManyField(Habilidades)
    full_name = models.CharField(verbose_name='Nombre completo',max_length=140,blank=True)
    avatar = models.ImageField(upload_to='empleado',blank=True,null=True)

    class Meta:
        verbose_name = 'Empleado'
        verbose_name_plural = 'Empleados'
        ordering = ['first_name']

    def __str__(self):
        return str(self.id) + ' - ' +  self.first_name + ' - ' + self.last_name


    

    

applications/persona/views.py
from django.db.models import query
from applications.departamento.models import Departamento
from django.shortcuts import render
from django.urls import reverse_lazy
from .models import Empleado 

from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    TemplateView,
    UpdateView,
    DeleteView,
    )

class InicioView(TemplateView): #Vista que carga la pagina home    
    template_name = 'home.html'


class ListAllEmpleados(ListView): #ListAllEmpleados trabaja con la lista generica ListView
    template_name = 'persona/list_all.html'
    context_object_name = 'lista_empleados'
    paginate_by = 4

    def get_queryset(self):
        palabra_clave = self.request.GET.get("keyword", '')  
        lista_trabajo = Empleado.objects.filter(
            full_name__icontains = palabra_clave 
        )
        return lista_trabajo


class ListaEmpleadosAdmin(ListView): 
    template_name = 'persona/lista-empleado-admin.html'
    context_object_name = 'lista_empleadoss'
    paginate_by = 5
    model = Empleado

class ListByArea(ListView): #ListAllEmpleados trabaja con la lista generica ListView
    template_name = 'persona/list_by_area.html'
    context_object_name = 'empleadoss'

    def get_queryset(self):
        area = self.kwargs['short_name'] #Indicamos que parametro de url queremos recoger
        lista_areas= Empleado.objects.filter(  
        departamento__short_name = area 
        ) 
        return lista_areas

#3 Listar los empleados pos trabajo*******PENDIENTE DE TERMINAR*********
class ListByJob(ListView):
    template_name = 'persona/list_by_job.html' 

    def get_queryset(self):
        trabajo = self.kwargs['job']
        lista_trabajo = Empleado.objects.filter(
        job = trabajo     
        )
        return lista_trabajo


class ListEmpleadByKw(ListView):
    template_name = 'persona/by_keyword.html'
    context_object_name = 'empleados'

    def get_queryset(self):
        palabra_clave = self.request.GET.get("keyword",)  #peticion GET que nos trae la id keyword del formulario
        lista_trabajo = Empleado.objects.filter( #Filtra por palabra clave para retornar lista
        first_name = palabra_clave   
        )
        return lista_trabajo
       

class ListHabilidadesEmpleado(ListView):
    template_name = 'persona/habilidades.html'
    context_object_name = 'skills'

    def get_queryset(self):
        empleado = Empleado.objects.get(id=6) #Recuperarmos al empleado por un dato especifico
        return empleado.habilidades.all()


class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = 'persona/detalle_empleado.html'
    

class SuccessView(TemplateView):
    template_name = "persona/success.html"


class EmpleadoCreateView(CreateView):
    model = Empleado
    template_name = "persona/add.html"
    fields = [#Campos que queremos que se vean en formulario crear cliente
        'first_name',
        'last_name',
        'job',
        'departamento',
        'habilidades',
        'avatar',
    ]
    success_url = reverse_lazy('persona_app:lista_empleados') #pagina de destino
    
    #Arreglar
    def form_valid(self, form): #Este metodo se realiza cuando se han espeficigado todos los campos del formulario
        empleado = form.save(commit=False) #Se recupera una instancia del formulario.Se guarda directamente en la bd
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        empleado.save()
        return super(EmpleadoCreateView,self).form_valid(form)


class EmpleadoUpdateView(UpdateView):
    model = Empleado
    template_name = "persona/update.html"
    fields = [
        'first_name',
        'last_name',
        'job',
        'departamento',
        'habilidades',
    ]
    success_url = reverse_lazy('persona_app:lista_empleados_admin') #pagina de destino
 

class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = "persona/delete.html"
    success_url = reverse_lazy('persona_app:lista_empleados_admin')

templates/persona/add.html
{% extends 'base.html' %}

{% block title %}Registrar empleado{% endblock title %}
    

{% block content %}
{% include 'includes/header.html' %}    

<div class="container my-4">
    <h1>Registrar empleado</h1>
    
    <form class="row my-3" method="POST" enctype="multipart/form-data">{% csrf_token %}
        
        <div class="col  form-group">
            <label>Nombre:</label>
            {{ form.first_name }}
            
        </div>
        <div class="col  form-group">
            <label>Apellidos:</label>
            {{ form.last_name }}
                
        </div>
        <div class="col form-group">
            <label>Trabajo:</label>
            {{ form.job }}
        </div>
        <div class="col form-group">
            <label>Departamento:</label>
            {{ form.departamento }}
        </div>
        <div class="col  form-group">
            <label>Skills:</label>
            {{ form.habilidades }}
        </div>
        <div class="col  form-group">
            <label>Imagen:</label>
            {{ form.avatar }}
        </div>
        <div class="col-12 my-5">
            <button type="submit" class="btn btn-success">Registrar Nuevo</button>
        </div>        
        
    </form>


</div>


{% endblock %}


<h1>Registrar empleado</h1>
<form method="POST">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Agregar</button>
</form>

templates/persona/by_keyword.html
<h1>Empleados por palabra clave</h1>

<form method="GET">{% csrf_token %}
    <input type="text" id="keyword" name="keyword" placeholder="Ingrese nombre aquí">
    <button type="submit">Buscar</button>
</form>

<h2>Resultados de la lista por palabra clave</h2>

<ul>
    
        
        {% for empleado in empleados %}
            <li>{{empleado}}</li>
        {% endfor %}
            
    
</ul>

templates/persona/delete.html
{% extends 'base.html' %}

{% block title %}Editar Empleado{% endblock title %}
    

{% block content %}
{% include 'includes/header.html' %}  

<div class="container my-4">
<h1>Eliminar Empleado</h1>

<form class="row my-3" method="POST">{% csrf_token %}

    <div class=" col alert alert-danger" role="alert">
        <P class="h5 mt-4">Confirme que desea eliminar el empleado {{ object.full_name}}</P>
        <button type="submit" class="btn btn-danger mt-4">Confirmar</button>
    </div>
    
</form>

</div>


{% endblock %}

templates/persona/detalle_empleado.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{object.full_name}}
{% endblock title %}
    

{% block content %}
{% include 'includes/header.html' %} 

<div class="container">
    <h1 class="text-center">Detalle del empleado</h1>
    <div class="row justify-content-center mt-5">
        <div class="card col-4" style="width: 18rem;">
            {% if empleado.avatar %}
                <img src="{{ empleado.avatar.url }}" class="card-img-top" alt="...">
            {% else %}
                <img src="{% static 'img/working.jpg' %} " class="card-img-top" alt="...">
                 
            {% endif %}
            <div class="card-body">
              <h5 class="card-title">{{ empleado.get_job_display }}</h5>
              <p class="card-text">{{ empleado.first_name }}</p>
              <p class="card-text">{{ empleado.last_name }}</p>
              <p class="card-text">{{ empleado.departamento.short_name }}</p>
              <div class="badge bg-primary text-wrap fs-6" style="width: 10rem;">
                Habilidades
              </div>
              <ul class="list-group list-group-flush">
                {% for habilidad  in empleado.habilidades.all  %}
                <li class="list-group-item">{{ habilidad.habilidad }}</li> 
                {% endfor %}
              </ul>
            </div>
            
          </div>
    </div>
</div>


{% endblock %}




{{empleado}}

<h2>Todos los datos</h2>
<p>{{empleado.first_name}}</p>
<p>{{empleado.last_name}}</p>
<p>{{empleado.job}}</p>
<p>{{empleado.departamento}}</p>
<p>{{empleado.habilidades}}</p>

templates/persona/eliminado.html
<h1>El empleado se borro perfectamente</h1>

templates/persona/habilidades.html
<h1>Lista de empleados por habilidades</h1>

<ul>
    
    {% for habilidad in skills %}
        <li>{{habilidad}}</li>
    {% endfor %}
        
</ul>

templates/persona/list_all.html
{% extends 'base.html' %}

{% block title %}Lista Empleados{% endblock %}

{% block content %}
{% include 'includes/header.html' %} 

<div class="container my-4">
    <h1>Lista de Empleados</h1>

    <form class="row mt-3" method="GET">{% csrf_token %}
        <div class="col-7 my-3">
            <input class="form-control" type="text" id="keyword" name="keyword" placeholder="Buscar Empleado">
        </div>
        <div class="col-2 my-3">
            <button type="submit" class="btn btn-primary">Buscar</button>
        </div>
        
    </form>
    

    <div class="row" >
      <div class="col-12 mt-4">
        <table class="table" >
            <thead>
              <tr>
                <th scope="col">ID</th>
                <th scope="col">NOMBRE</th>
                <th scope="col">APELLIDOS</th>
                <th scope="col">DEPARTAMENTO</th>
                <th scope="col">ACCION</th>
              </tr>
            </thead>
            <tbody>
              {% for empleado in lista_empleados %} 
              <tr>
                <td>{{ empleado.id }}</td>
                <td>{{ empleado.first_name }}</td>
                <td>{{ empleado.last_name }}</td>
                <td>{{ empleado.departamento }}</td>
                <td><a class="btn btn-danger" href="{% url 'persona_app:detalle-empleado' empleado.id %}" role="button">Ver</a></td>
              </tr>
              {% endfor %} 
            </tbody>
        </table>
      </div>
      <div class="col-12">
        
        {% if is_paginated %}
        <nav aria-label="Page navigation example">
          <ul class="pagination">
            
            {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number}}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li> 
            {% endif %}
            
            {% for pagina in paginator.page_range %}
            
            <li class="page-item"><a class="page-link" href="?page={{ pagina }}">{{ pagina }}</a></li> 
            {% endfor %}
              
            {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number}}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
            {% endif %}
          
          </ul>
        </nav>
        {% endif %}
          
      </div>
    </div>


</div>
    

{% endblock %}

    

templates/persona/list_by_area.html
{% extends 'base.html' %}


{% block title %}Lista Empleados por departamento{% endblock %}
    
{% block content %}
{% include 'includes/header.html' %} 

<div class="container">
<h1>Lista de empleados por departamento</h1>

<div class="row" >
    <div class="col-12 mt-4">
      <table class="table" >
          <thead>
            <tr>
              <th scope="col">ID</th>
              <th scope="col">NOMBRE</th>
              <th scope="col">APELLIDOS</th>
              <th scope="col">DEPARTAMENTO</th>
              <th scope="col">ACCION</th>
            </tr>
          </thead>
          <tbody>
            {% for empleado in empleadoss %} 
            <tr>
              <td>{{ empleado.id }}</td>
              <td>{{ empleado.first_name }}</td>
              <td>{{ empleado.last_name }}</td>
              <td>{{ empleado.departamento }}</td>
              <td><a class="btn btn-danger" href="{% url 'persona_app:detalle-empleado' empleado.id %}" role="button">Ver</a></td>
            </tr>
            {% endfor %} 
          </tbody>
      </table>
    </div>
 </div>
{% endblock %}
<h1>lista de empleados</h1>

<ul>
   
   {% for empleado in empleadoss %}
        <li>
            {{ empleado }}
        </li>
   {% endfor %}
       
</ul>

templates/persona/list_by_job.html
<h1>Listado de los empleados por trabajo</h1>

<ul>
    {% for i in object_list %}
    <li>
        {{i}}
    </li>
    {% endfor %}
</ul>

templates/persona/lista-empleado-admin.html
{% extends 'base.html' %}

{% block title %}Lista Empleados Administrador{% endblock %}

{% block content %}
{% include 'includes/header.html' %} 

<div class="container my-4">
    <h1>Lista de Empleados Admistracion</h1>
    
    <div class="row" >
      <div class="col-12 mt-4">
        <table class="table" >
            <thead>
              <tr>
                <th scope="col">ID</th>
                <th scope="col">NOMBRE</th>
                <th scope="col">APELLIDOS</th>
                <th scope="col">DEPARTAMENTO</th>
                <th scope="col">ACCION</th>
              </tr>
            </thead>
            <tbody>
              {% for empleado in lista_empleadoss %} 
              <tr>
                <td>{{ empleado.id }}</td>
                <td>{{ empleado.first_name }}</td>
                <td>{{ empleado.last_name }}</td>
                <td>{{ empleado.departamento }}</td>
                <td><a class="btn btn-success" href="{% url 'persona_app:modificar-empleado' empleado.id %}" role="button">Editar</a></td>
                <td><a class="btn btn-warning" href="{% url 'persona_app:eliminar-empleado' empleado.id %}" role="button">Eliminar</a></td>
              </tr>
              {% endfor %} 
            </tbody>
        </table>
    </div>
      <div class="col-12">
        
        {% if is_paginated %}
        <nav aria-label="Page navigation example">
          <ul class="pagination">
            
            {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number}}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li> 
            {% endif %}
            
            {% for pagina in paginator.page_range %}
            
            <li class="page-item"><a class="page-link" href="?page={{ pagina }}">{{ pagina }}</a></li> 
            {% endfor %}
              
            {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number}}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
            {% endif %}
          
          </ul>
        </nav>
        {% endif %}
          
      </div>
    </div>


</div>
    

{% endblock %}

    

templates/persona/success.html
<h1>Se guardó correctamente el empleado</h1>

templates/persona/update.html
{% extends 'base.html' %}

{% block title %}Editar Empleado{% endblock title %}
    

{% block content %}
{% include 'includes/header.html' %}    

<div class="container my-4">
    <h1>Modificar empleado</h1>
    
    <form class="row my-3" method="POST">{% csrf_token %}
        
        <div class="col form-group">
            <label>Nombre:</label>
            {{ form.first_name }}
            
        </div>
        <div class="col form-group">
            <label>Apellidos:</label>
            {{ form.last_name }}
                
        </div>
        <div class="col form-group">
            <label>Trabajo:</label>
            {{ form.job }}
            
        </div>
        <div class="col form-group">
            <label>Departamento:</label>
            {{ form.departamento }}
            
        </div>
        <div class="col  form-group">
            <label>Skills:</label>
            {{ form.habilidades }}
            
        </div>
        <div class="col-12">
            <button type="submit" class="btn btn-primary">Actualizar</button>
        </div>        
    
    </form>

</div>


{% endblock %}
    