applications/departamento/urls.py
from django.contrib import admin
from django.urls import path

from .import views

app_name = "departamento_app"


urlpatterns = [
    path('departamento-lista/',views.DepartamentoListView.as_view(), name='departamento-lista'),
    path('nuevo-departamento/',views.NuevoDepartamentoview.as_view(), name='nuevo_departamento'),
]

applications/persona/urls.py
from django.contrib import admin
from django.urls import path

from .import views


app_name = "persona_app" #Nombre de todo el conjunto de direcciones

urlpatterns = [
    
    path('',views.InicioView.as_view(),name='inicio'),
    path('lista-empleados-admin/',views.ListaEmpleadosAdmin.as_view(),name='lista_empleados_admin'),
    path('lista-todos-empleados/',views.ListAllEmpleados.as_view(),name='lista_empleados'),
    path('lista-por-area/<short_name>',views.ListByArea.as_view(),name='empleados-area'),
    path('lista-por-trabajo/<short_name>',views.ListByJob.as_view()),
    path('buscar-empleado/',views.ListEmpleadByKw.as_view()),
    path('habilidades-empleado/',views.ListHabilidadesEmpleado.as_view()),
    path('ver-empleado/<pk>/',views.EmpleadoDetailView.as_view(),name='detalle-empleado'),
    path('crear-empleado/',views.EmpleadoCreateView.as_view(),name='crear_empleado'),
    path('registro-realizado/',views.SuccessView.as_view(),name='success'),
    path('update-empleado/<pk>/',views.EmpleadoUpdateView.as_view(),name='modificar-empleado'),
    path('eliminar-empleado/<pk>/',views.EmpleadoDeleteView.as_view(),name='eliminar-empleado'),
    path('empleado-eliminado/',views.EmpleadoDeleteView.as_view(),name='eliminado'),
   
    ]

empleado/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.departamento.urls')),
    path('', include('applications.persona.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
<nav class="navbar navbar-light bg-light navbar-expand-lg">
  <div class="container-fluid">
      <a href="{% url 'persona_app:inicio' %}" class="navbar-brand text-danger fs-4">Empleados-app</a>
      <button 
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse nav justify-content-center"  id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a href="{% url 'persona_app:inicio' %}" class="nav-link {% if request.path == '/' %}active{% endif %}">Home</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'persona_app:lista_empleados' %}" class="nav-link {% if request.path == '/lista-todos-empleados/' %}active{% endif %}">Empleados</a>
          </li>
          <li class="nav-item"> 
            <a href="{% url 'departamento_app:departamento-lista' %}" class="nav-link {% if request.path == '/departamento-lista/' %}active{% endif %}">Departamentos</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'persona_app:lista_empleados_admin' %}" class="nav-link {% if request.path == '/lista-empleados-admin/' %}active{% endif %}">Administrar</a>
          </li>
          
        </ul>

      </div>
      <div class="d-flex ">
        <a class="btn btn-outline-dark mx-2" href="{% url 'departamento_app:nuevo_departamento' %}" role="button">Nuevo departamento</a>
        <a class="btn btn-outline-primary mx-2" href="{% url 'persona_app:crear_empleado' %}" role="button">Nuevo Empleado</a>
      </div>
    </div>
  
</nav>


  