applications/departamento/urls.py
from django.contrib import admin
from django.urls import path

from .import views

app_name = "departamento_app"


urlpatterns = [
    path('departamento-lista/',views.DepartamentoListView.as_view(), name='departamento-lista'),
    path('nuevo-departamento/',views.NuevoDepartamentoview.as_view(), name='nuevo_departamento'),
]

applications/persona/urls.py
from django.contrib import admin
from django.urls import path

from .import views


app_name = "persona_app" #Nombre de todo el conjunto de direcciones

urlpatterns = [
    
    path('',views.InicioView.as_view(),name='inicio'),
    path('lista-empleados-admin/',views.ListaEmpleadosAdmin.as_view(),name='lista_empleados_admin'),
    path('lista-todos-empleados/',views.ListAllEmpleados.as_view(),name='lista_empleados'),
    path('lista-por-area/<short_name>',views.ListByArea.as_view(),name='empleados-area'),
    path('lista-por-trabajo/<short_name>',views.ListByJob.as_view()),
    path('buscar-empleado/',views.ListEmpleadByKw.as_view()),
    path('habilidades-empleado/',views.ListHabilidadesEmpleado.as_view()),
    path('ver-empleado/<pk>/',views.EmpleadoDetailView.as_view(),name='detalle-empleado'),
    path('crear-empleado/',views.EmpleadoCreateView.as_view(),name='crear_empleado'),
    path('registro-realizado/',views.SuccessView.as_view(),name='success'),
    path('update-empleado/<pk>/',views.EmpleadoUpdateView.as_view(),name='modificar-empleado'),
    path('eliminar-empleado/<pk>/',views.EmpleadoDeleteView.as_view(),name='eliminar-empleado'),
    path('empleado-eliminado/',views.EmpleadoDeleteView.as_view(),name='eliminado'),
   
    ]

empleado/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.departamento.urls')),
    path('', include('applications.persona.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamento/models.py
from typing import ChainMap
from django.db import models

# Create your models here.
class Departamento(models.Model):
    name = models.CharField(verbose_name='Nombre', max_length=100)
    short_name = models.CharField(verbose_name='Nombre corto', max_length=50, unique=True)
    anulate = models.BooleanField(verbose_name='Anulado',default=False)

    class Meta:
        verbose_name = 'Departamento'
        verbose_name_plural = 'Departamentos'
        ordering = ['name']

    def __str__(self):
        return str(self.id) + ' - ' +  self.name + ' - ' + self.short_name 

applications/departamento/forms.py
from django import forms



class NewDepartamentoForm(forms.Form):
    nombre = forms.CharField(max_length=70)
    apellidos = forms.CharField(max_length=70)
    departamento = forms.CharField(max_length=70)
    nombre_corto = forms.CharField(max_length=50)

applications/departamento/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from applications.persona.models import Empleado
from .models import Departamento
from .forms import NewDepartamentoForm
from django.views.generic import ListView


class DepartamentoListView(ListView):
    model = Departamento
    template_name = 'departamento/departamento-lista.html'
    context_object_name = 'departamentos'


class NuevoDepartamentoview(FormView):
    template_name = 'departamento/nuevo_departamento.html'
    form_class = NewDepartamentoForm
    success_url = '/'
    
    def form_valid(self, form): 
        print('*********Estamos en el formvalid')
        
        depart = Departamento(  #Se crea una instancia de modelo departamento
            name = form.cleaned_data['departamento'], #departamento de forms, de la clase NewDepartamentforms
            short_name = form.cleaned_data['nombre_corto'],
        )
        depart.save()

        nombre = form.cleaned_data['nombre']
        apellidos = form.cleaned_data['apellidos']
        Empleado.objects.create(
            first_name = nombre,
            last_name = apellidos,
            job = '1',
            departamento = depart
        )
        return super(NuevoDepartamentoview,self).form_valid(form)
        
         



        

templates/departamento/departamento-lista.html
{% extends 'base.html' %}

{% block title %}Lista Departamentos{% endblock %}

{% block content %}
{% include 'includes/header.html' %} 

<div class="container my-4">
    <h1>Departamentos de la Empresa</h1>
    <div class="col-12 mt-4">
        <table class="table" >
            <tbody>
              
              {% for departamento in departamentos  %}
              <tr>
                <td>{{ departamento.name }}</td>
                <td>{{ departamento.short_name }}</td>
                <td><a class="btn btn-danger" href="{% url 'persona_app:empleados-area' departamento.short_name %}" role="button">Ver Empleados</a></td>
              </tr>
              {% endfor %}
            </tbody>
        </table>
    </div>


</div>
                  
              
                  
            
              






{% endblock %}

templates/departamento/nuevo_departamento.html
{% extends 'base.html' %}

{% block title %}Nuevo Departamento{% endblock title %}
    

{% block content %}
{% include 'includes/header.html' %}    

<div class="container my-4">
    <h1>Registrar Nuevo Departamento</h1>
    
    <form class="row my-3" method="POST">{% csrf_token %}
        
        <div class="col m-3 form-group">
            <label>Nombre:</label>
            {{ form.nombre }}
            
        </div>
        <div class="col m-3 form-group">
            <label>Apellidos:</label>
            {{ form.apellidos }}
        </div>
        <div class="col m-3 form-group">
            <label>Departamento:</label>
            {{ form.departamento }}
        </div>
        <div class="col m-3 form-group">
            <label>Nombre Corto Departamento:</label>
            {{ form.nombre_corto }}
        </div>
        
        <div class="col-12 m-3">
            <button type="submit" class="btn btn-success">Registrar Nuevo</button>
        </div>        
        
    </form>


</div>


{% endblock %}





<h1>Registrar nuevo departamento</h1>

<form method="POST">{% csrf_token %}
    <h2>Datos empleado</h2>
    <p>
        {{form.nombre}}
    </p>
    <p>
        {{form.apellidos}}
    </p>
    <h2>Datos de departamento</h2>
    <p>
        {{form.departamento}}
    </p>
    <p>
        {{form.nombre_corto}}
    </p>

    
    <button type="submit">Guardar</button>
</form>